spring:
  datasource:
    password: 1
    url: jdbc:postgresql://localhost:5433/thymleaf-crud
    username: postgres
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  cache: false


